import "../globals.css";
import SideMenu from "../components/SideMenu";
import { ProjectProvider } from "../components/projectsApi";
import { TaskProvider } from "../components/tasksApi";

// export const metadata = {
//   title: "Task Management SaaS",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <ProjectProvider>
      <TaskProvider>
        <div className="flex h-screen w-screen">
          <SideMenu />
          {children}
        </div>
      </TaskProvider>
    </ProjectProvider>
  );
}
